services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=sqluser
      - DB_PASSWORD=password
      - DB_NAME=db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YouWillNotGuessThis
      MYSQL_DATABASE: db
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/my.cnf  # Mount the custom my.cnf here
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
